#! /bin/bash

base_signed_url="http://archive.ubuntu.com/ubuntu/dists/trusty/main/uefi/grub2-amd64/current"

wget "$base_signed_url/gcdx64.efi.signed"
wget "$base_signed_url/grubx64.efi.signed"
wget "$base_signed_url/grubnetx64.efi.signed"
wget "$base_signed_url/version"
