#! /bin/sh
set -e

if [ -d /target/home/oem ]; then
	for file in \
	    /usr/share/applications/oem-config-prepare-gtk.desktop \
	    /usr/share/applications/kde4/oem-config-prepare-kde.desktop; do
		if [ -f "/target$file" ]; then
			name=$(basename "$file")
			cat > /target/home/oem/.config/plank/dock1/launchers/$name.dockitem <<EOF
[PlankItemsDockItemPreferences]
Launcher=$file
Sort=-1
EOF
			break
		fi
	done
fi

exit 0
