#! /bin/sh
set -e

if [ -d /target/home/oem ]; then
	for file in \
		/usr/share/applications/oem-config-prepare-gtk.desktop \
		/usr/share/applications/kde4/oem-config-prepare-kde.desktop; do
		if [ -f "/target$file" ]; then
			chroot /target install -d -o oem -g oem \
				/home/oem/.config/plank/dock1/launchers
			name=$(basename "$file")
			echo "[PlankItemsDockItemPreferences]
Launcher=$file
Sort=-1" > /target/home/oem/.config/plank/dock1/launchers/${name%.*}.dockitem
			break
		fi
	done
fi

exit 0
