/* alm.c generated by valac 0.14.2, the Vala compiler
 * generated from alm.vala, do not modify */

/*
 * Alm.vala
 * Copyright (C) 2012 Seif Lotfy <seif@lotfy.com>
 * Copyright (C) 2012 Intel Corp.
 *               Authored by: Seif Lotfy <seif.lotfy@collabora.co.uk>
 * 
alm is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 * 
 * alm is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.";
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define ALM_TYPE_MAIN (alm_main_get_type ())
#define ALM_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ALM_TYPE_MAIN, AlmMain))
#define ALM_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ALM_TYPE_MAIN, AlmMainClass))
#define ALM_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ALM_TYPE_MAIN))
#define ALM_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ALM_TYPE_MAIN))
#define ALM_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ALM_TYPE_MAIN, AlmMainClass))

typedef struct _AlmMain AlmMain;
typedef struct _AlmMainClass AlmMainClass;
typedef struct _AlmMainPrivate AlmMainPrivate;

#define ALM_TYPE_ACTIVITY_LOG_MANAGER (alm_activity_log_manager_get_type ())
#define ALM_ACTIVITY_LOG_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ALM_TYPE_ACTIVITY_LOG_MANAGER, AlmActivityLogManager))
#define ALM_ACTIVITY_LOG_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ALM_TYPE_ACTIVITY_LOG_MANAGER, AlmActivityLogManagerClass))
#define ALM_IS_ACTIVITY_LOG_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ALM_TYPE_ACTIVITY_LOG_MANAGER))
#define ALM_IS_ACTIVITY_LOG_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ALM_TYPE_ACTIVITY_LOG_MANAGER))
#define ALM_ACTIVITY_LOG_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ALM_TYPE_ACTIVITY_LOG_MANAGER, AlmActivityLogManagerClass))

typedef struct _AlmActivityLogManager AlmActivityLogManager;
typedef struct _AlmActivityLogManagerClass AlmActivityLogManagerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _AlmMain {
	GtkWindow parent_instance;
	AlmMainPrivate * priv;
};

struct _AlmMainClass {
	GtkWindowClass parent_class;
};


static gpointer alm_main_parent_class = NULL;

GType alm_main_get_type (void) G_GNUC_CONST;
enum  {
	ALM_MAIN_DUMMY_PROPERTY
};
AlmMain* alm_main_new (void);
AlmMain* alm_main_construct (GType object_type);
AlmActivityLogManager* alm_activity_log_manager_new (void);
AlmActivityLogManager* alm_activity_log_manager_construct (GType object_type);
GType alm_activity_log_manager_get_type (void) G_GNUC_CONST;
void alm_main_on_destroy (GtkWidget* window, AlmMain* self);
static void _alm_main_on_destroy_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static gint alm_main_main (gchar** args, int args_length1);


static void _alm_main_on_destroy_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	alm_main_on_destroy (_sender, self);
}


AlmMain* alm_main_construct (GType object_type) {
	AlmMain * self = NULL;
	const gchar* _tmp0_ = NULL;
	AlmActivityLogManager* _tmp1_;
	AlmActivityLogManager* _tmp2_;
	AlmActivityLogManager* widget;
	self = (AlmMain*) g_object_new (object_type, NULL);
	_tmp0_ = _ ("Activity Log Manager");
	gtk_window_set_title ((GtkWindow*) self, _tmp0_);
	_tmp1_ = alm_activity_log_manager_new ();
	_tmp2_ = g_object_ref_sink (_tmp1_);
	widget = _tmp2_;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) widget);
	gtk_widget_show_all ((GtkWidget*) self);
	g_signal_connect_object ((GtkWidget*) self, "destroy", (GCallback) _alm_main_on_destroy_gtk_widget_destroy, self, 0);
	_g_object_unref0 (widget);
	return self;
}


AlmMain* alm_main_new (void) {
	return alm_main_construct (ALM_TYPE_MAIN);
}


void alm_main_on_destroy (GtkWidget* window, AlmMain* self) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	gtk_main_quit ();
}


static gint alm_main_main (gchar** args, int args_length1) {
	gint result = 0;
	GtkApplication* _tmp0_;
	GtkApplication* alm;
	AlmMain* _tmp1_;
	AlmMain* _tmp2_;
	AlmMain* window;
	gtk_init (&args_length1, &args);
	_tmp0_ = gtk_application_new ("org.zeitgeist.Alm", G_APPLICATION_FLAGS_NONE);
	alm = _tmp0_;
	_tmp1_ = alm_main_new ();
	_tmp2_ = g_object_ref_sink (_tmp1_);
	window = _tmp2_;
	gtk_application_add_window (alm, (GtkWindow*) window);
	gtk_main ();
	result = 0;
	_g_object_unref0 (window);
	_g_object_unref0 (alm);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return alm_main_main (argv, argc);
}


static void alm_main_class_init (AlmMainClass * klass) {
	alm_main_parent_class = g_type_class_peek_parent (klass);
}


static void alm_main_instance_init (AlmMain * self) {
}


GType alm_main_get_type (void) {
	static volatile gsize alm_main_type_id__volatile = 0;
	if (g_once_init_enter (&alm_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AlmMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) alm_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AlmMain), 0, (GInstanceInitFunc) alm_main_instance_init, NULL };
		GType alm_main_type_id;
		alm_main_type_id = g_type_register_static (GTK_TYPE_WINDOW, "AlmMain", &g_define_type_info, 0);
		g_once_init_leave (&alm_main_type_id__volatile, alm_main_type_id);
	}
	return alm_main_type_id__volatile;
}



